config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/auth/google_oauth2/callback', to: 'google_oauth_sessions#create'
  
  namespace :api do
    namespace :v1 do
      resources :rehearsals, only: [:update] do
        resources :notes, only: [:index, :create]
      end
    end
  end
  
  resources :users, only: [:show, :new, :create]
  resources :notes, only: [:update]

  resources :companies, only: [:new, :create] do
    resources :productions, only: [:new, :create] do
      resources :rehearsals, only: [:new, :create]
      resources :teams, only: [:new, :create]
    end
  end

  namespace :company, path: ':company_name' do
    get '/:production_title/teams/:id', to: 'teams#show', as: 'production_team'
    get '/:production_title/:id', to: 'rehearsals#show', as: 'production_rehearsal'
    patch '/:prouction_title/:id', to: 'rehearsals#update', as: 'production_rehearsal_update'
    get '/:production_title', to: 'productions#show', as: 'production'
  end
  
  get '/:company_name', to: 'companies#show', as: 'company'
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :productions
  has_many :company_managers
  
  validates :name, presence: true, uniqueness: true

  scope :where_manager, ->(user_id) { joins(:company_managers).where('company_managers.user_id = ?', user_id) }
  scope :where_member, ->(user_id) { joins(productions: :memberships).where('memberships.user_id = ?', user_id) }

  def managers
    User.joins(:managements).where('company_managers.company_id = ?', self.id)
  end

end

app/models/production.rb
class Production < ApplicationRecord
  belongs_to :company
  has_many :rehearsals
  has_many :teams
  has_many :memberships, through: :teams
  has_many :company_managers, through: :company
  has_many :notes, through: :rehearsals

  validates :title, presence: true

  scope :where_manager, ->(user_id) { joins(company: :company_managers).where('company_managers.user_id = ?', user_id) }
  scope :where_member, ->(user_id) { joins(teams: :memberships).where('memberships.user_id = ?', user_id) } 
  
  def members
    User.joins(memberships: :team).where('teams.production_id=?', self.id)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource

  def show
    @company = Company.find_by(name: params[:company_name])
  end
  
  def new 
    @company = Company.new
  end

  def create
    company = Company.new(company_params)
    if company.save
      company.company_managers.create(user: current_user)
      flash[:success] = "Your company has been created!"
      redirect_to company_path(company.name)
    else
      flash[:warning] = "Please fill in all the required fields"
      render :new
    end
  end

  private
    def company_params
      params.require('company').permit('name', 'location', 'logo_url')
    end
end

app/controllers/company/productions_controller.rb
class Company::ProductionsController < ApplicationController
  load_and_authorize_resource
  def show
    company = Company.find_by(name: params[:company_name])
    @production = company.productions.find_by(title: params[:production_title])
  end
end

app/controllers/company/rehearsals_controller.rb
class Company::RehearsalsController < ApplicationController
  load_and_authorize_resource
  def show
    company = Company.find_by(name: params[:company_name])
    production = company.productions.where(title: params[:production_title]).first
    @rehearsal = production.rehearsals.where(id: params[:id]).first
  end

  def update
    company = Company.find_by(name: params[:company_name])
    production = company.productions.where(title: params[:production_title]).first
    rehearsal = production.rehearsals.new(rehearsal_params)
    if rehearsal.save
      flash[:success] = "Rehearsal updated"
      redirect_to company_production_rehearsal_path(company.name, production.title, rehearsal.id)
    else
      flash[:danger] = "Please fill in a description"
      render :show
    end
  end

  private
  def rehearsal_params 
    params.require('rehearsal').permit('date', 'location', 'description')
  end
end

app/controllers/company/teams_controller.rb
class Company::TeamsController < ApplicationController
  def show
    @team = Team.find(params[:id])
  end
end

app/controllers/productions_controller.rb
class ProductionsController < ApplicationController
  def new
    @company = Company.find(params[:company_id])
    @production = @company.productions.new
    authorize! :manage, @production
  end

  def create
    company = Company.find(params[:company_id])
    production = company.productions.new(production_params)
    if production.save
      flash[:success] = "Your production was created!"
      redirect_to company_production_path(company.name, production.title)
    else
      flash[:danger] = "Please fill in all required fields."
      render :new
    end
  end

  private
    def production_params
      params.require('production').permit('title', 'season', 'logo_url')
    end
end

app/views/company/productions/show.html.erb
<main class='production-show'>
  <section class='production-info'>
    <%= image_tag(@production.logo_url) %>

    <h2><%= @production.title %></h2>
    <h4><%= @production.season %></h4>
    <h4><%= @production.company.name %></h4>
    
    <% if can? :update, @production %> 
      <%= link_to "Create a new team", new_company_production_team_path(@production.company, @production), class: 'teal-button' %>
    <% end %>
    
      <% @production.teams.each do |team| %>
        <div class='team'><%= link_to team.name, company_production_team_path(@production.company.name, @production.title, team.id) %></div>
      <% end %>
  </section>

  <section class='production-rehearsals'>
    <% if can? :update, @production %> 
      <%= link_to "Create a new rehearsal", new_company_production_rehearsal_path(@production.company, @production), class: 'orange-button' %>
    <% end %>
      <% @production.rehearsals.each do |rehearsal| %>
        <div class='rehearsal'>
          <%= link_to "#{rehearsal.date}, #{rehearsal.location}", company_production_rehearsal_path(@production.company.name, @production.title, rehearsal.id) %>
        </div>
      <% end %>
  </section>

  <section class='production-notes'>
    <h4>Most Recent Notes</h4>
    <div class='notes'>
      <% @production.teams.each do |team| %>
        <% if team.notes.inactive != 0 %>
          <div class = 'team'>
          <h4><%= team.name %></h4> 
          <% team.notes.inactive.each do |note| %>    
            <div class='note'>
              <p><%= note.content %></p>
              <div class="status <%= note.status %>"><%= note.status %></div>
            </div>
          <% end %>
          </div>
        <% end %>
      <% end %>
      </div>  
    </div>
  </section>
</main>