config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/auth/google_oauth2/callback', to: 'google_oauth_sessions#create'
  
  namespace :api do
    namespace :v1 do
      resources :rehearsals, only: [:update] do
        resources :notes, only: [:index, :create]
      end
    end
  end
  
  resources :users, only: [:show, :new, :create]
  resources :notes, only: [:update]

  resources :companies, only: [:new, :create] do
    resources :productions, only: [:new, :create] do
      resources :rehearsals, only: [:new, :create]
      resources :teams, only: [:new, :create]
    end
  end

  namespace :company, path: ':company_name' do
    get '/:production_title/teams/:id', to: 'teams#show', as: 'production_team'
    get '/:production_title/:id', to: 'rehearsals#show', as: 'production_rehearsal'
    patch '/:prouction_title/:id', to: 'rehearsals#update', as: 'production_rehearsal_update'
    get '/:production_title', to: 'productions#show', as: 'production'
  end
  
  get '/:company_name', to: 'companies#show', as: 'company'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :memberships
  has_many :managements, class_name: 'CompanyManager'
  has_many :companies, through: :managements
  has_many :productions, through: :memberships

  validates :name, presence: true
  validates :email, presence: true
  validates :uid, uniqueness: true

  def self.from_oauth(uid, profile)
    user = User.where(:uid => uid).first
    if user
      user
    else
      User.create(uid: uid, 
                  name: profile[:name],
                  email: profile[:email],
                  image_url: profile[:image])
    end
  end

  def is_manager?
    managements.length != 0
  end

  def is_member?
    memberships.length != 0
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save 
      flash[:success] = "Welcome! Your account was created."
      redirect_to user_path(user)
    else
      flash[:danger] = "Please fill in all required fields"
      render :new
    end
  end

  private

    def user_params
      params.require('user').permit('name', 'email', 'slack_name', 'image_url')
    end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :slack_name %>
  <%= f.text_field :slack_name %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "#{verb} Account" %>
<% end %>

app/views/users/new.html.erb
<h1>Create an Account</h2>
<%= link_to "Login with Google", "/auth/google_oauth2" %> 

<%= render partial: 'form', locals: { user: @user, verb: "Create" }  %>

app/views/users/show.html.erb
<main class='user-show'>
  <section class='user-content'>
    <h2>Your Account</h2>
    <% if @user.image_url %>
      <%= image_tag(@user.image_url) %>
    <% end %>
    <%= @user.name %>
    <%= link_to "Create a new company", new_company_path, class: 'orange-button' %>
  </section>

  <section class='user-companies'>
    <% @user.managements.each do |management| %>
      <div class='company-card'>
        <%= image_tag(management.company.logo_url) %>
        <h4><%= link_to management.company.name, company_path(management.company.name) %></h4>
      </div>
    <% end %>
  </section>
</main>