config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/auth/google_oauth2/callback', to: 'google_oauth_sessions#create'
  
  namespace :api do
    namespace :v1 do
      resources :rehearsals, only: [:update] do
        resources :notes, only: [:index, :create]
      end
    end
  end
  
  resources :users, only: [:show, :new, :create]
  resources :notes, only: [:update]

  resources :companies, only: [:new, :create] do
    resources :productions, only: [:new, :create] do
      resources :rehearsals, only: [:new, :create]
      resources :teams, only: [:new, :create]
    end
  end

  namespace :company, path: ':company_name' do
    get '/:production_title/teams/:id', to: 'teams#show', as: 'production_team'
    get '/:production_title/:id', to: 'rehearsals#show', as: 'production_rehearsal'
    patch '/:prouction_title/:id', to: 'rehearsals#update', as: 'production_rehearsal_update'
    get '/:production_title', to: 'productions#show', as: 'production'
  end
  
  get '/:company_name', to: 'companies#show', as: 'company'
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :productions
  has_many :company_managers
  
  validates :name, presence: true, uniqueness: true

  scope :where_manager, ->(user_id) { joins(:company_managers).where('company_managers.user_id = ?', user_id) }
  scope :where_member, ->(user_id) { joins(productions: :memberships).where('memberships.user_id = ?', user_id) }

  def managers
    User.joins(:managements).where('company_managers.company_id = ?', self.id)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource

  def show
    @company = Company.find_by(name: params[:company_name])
  end
  
  def new 
    @company = Company.new
  end

  def create
    company = Company.new(company_params)
    if company.save
      company.company_managers.create(user: current_user)
      flash[:success] = "Your company has been created!"
      redirect_to company_path(company.name)
    else
      flash[:warning] = "Please fill in all the required fields"
      render :new
    end
  end

  private
    def company_params
      params.require('company').permit('name', 'location', 'logo_url')
    end
end

app/controllers/company/productions_controller.rb
class Company::ProductionsController < ApplicationController
  load_and_authorize_resource
  def show
    company = Company.find_by(name: params[:company_name])
    @production = company.productions.find_by(title: params[:production_title])
  end
end

app/controllers/company/rehearsals_controller.rb
class Company::RehearsalsController < ApplicationController
  load_and_authorize_resource
  def show
    company = Company.find_by(name: params[:company_name])
    production = company.productions.where(title: params[:production_title]).first
    @rehearsal = production.rehearsals.where(id: params[:id]).first
  end

  def update
    company = Company.find_by(name: params[:company_name])
    production = company.productions.where(title: params[:production_title]).first
    rehearsal = production.rehearsals.new(rehearsal_params)
    if rehearsal.save
      flash[:success] = "Rehearsal updated"
      redirect_to company_production_rehearsal_path(company.name, production.title, rehearsal.id)
    else
      flash[:danger] = "Please fill in a description"
      render :show
    end
  end

  private
  def rehearsal_params 
    params.require('rehearsal').permit('date', 'location', 'description')
  end
end

app/controllers/company/teams_controller.rb
class Company::TeamsController < ApplicationController
  def show
    @team = Team.find(params[:id])
  end
end

app/views/companies/_form.html.erb
<%= form_for @company, :html => {class: 'form'} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :logo_url %>
  <%= f.text_field :logo_url %>

  <%= f.submit %>
<% end %>

app/views/companies/new.html.erb
<%= render partial: 'form', locals: { user: @user } %>

app/views/companies/show.html.erb
<main class='company-show'>
  <section class='company-info'>
    <%= image_tag(@company.logo_url) %>
    <h2><%= @company.name %></h2>
    <h4><%= @company.location %></h4>
    <% if can? :manage, @company %>
      <%= link_to "Create a new production", new_company_production_path(@company), class: 'orange-button' %>
    <% end %>
    <h4>Managers</h4>
    <hr>
    <ul>
      <% @company.company_managers.each do |manager| %>
        <li><%= manager.user.name %></li>
      <% end %>
    </ul>
  </section>

  <section class='company-productions'>
    <% @company.productions.each do |production| %>
      <div class='production-card'>
        <%= image_tag(production.logo_url) %>
        <h4><%= link_to production.title, company_production_path(@company.name, production.title) %></h4> 
      </div>
    <% end %>

  </section>
</main>